.TH MYSTRNCPY 3 "September 2026" "Version 0.4.1" "OS Assignment"
.SH NAME
mystrncpy \- copy a limited number of characters
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.br
.B int mystrncpy(char *dest, const char *src, int n);
.SH DESCRIPTION
The mystrncpy function copies up to n characters from the source string to the destination string. Remaining positions are filled with null characters when required.
.SH AUTHOR
M. Samiullah

