.TH MYSTRCPY 3 "September 2026" "Version 0.4.1" "OS Assignment"
.SH NAME
mystrcpy \- copy one string to another
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.br
.B int mystrcpy(char *dest, const char *src);
.SH DESCRIPTION
The mystrcpy function copies the source string into the destination string and returns the number of characters copied.
.SH AUTHOR
M. Samiullah 
