.TH MYSTRCAT 3 "September 2026" "Version 0.4.1" "OS Assignment"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.br
.B int mystrcat(char *dest, const char *src);
.SH DESCRIPTION
The mystrcat function appends the source string to the end of the destination string and returns the resulting string length.
.SH AUTHOR
M. Samiullah
